### ISSUE TITLE
HTTP 500 from service

### ISSUE THREAD

**Issue by martincostello** [Microsoft/dotnet-apiport#312]
The tool appears to be no longer working due to an HTTP 500 from the back-end using the console application and the VSIX:

**Console output:**
```
Microsoft (R) API Portability Analyzer v1.2.1.alpha.00031
Copyright (C) Microsoft Corporation. All rights reserved.

This tool analyzes .NET assemblies to determine possible problems moving between .NET platforms (such as
Windows Store, desktop, Mono, .NET Core, etc) as well as between .NET Framework versions (ie 4.x->4.y).

To learn more about how this tool works, including the data we are collecting,
go here - http://go.microsoft.com/fwlink/?LinkId=397652

Detecting assembly references                     [Done]
Sending data to service                           [Failed]
ApiPort.exe Error: 0 : System.AggregateException: One or more errors occurred. ---> Microsoft.Fx.Portability.PortabilityAnalyzerException: There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
   at Microsoft.Fx.Portability.CompressedHttpClient.<CallInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.CompressedHttpClient.<CallAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortService.<SendAnalysisAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<GetResultFromServiceAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<GetAnalysisResultAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<WriteAnalysisReportsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPort.ConsoleApiPort.<AnalyzeAssembliesAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ApiPort.Program.Main(String[] args)
---> (Inner Exception #0) Microsoft.Fx.Portability.PortabilityAnalyzerException: There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
   at Microsoft.Fx.Portability.CompressedHttpClient.<CallInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.CompressedHttpClient.<CallAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortService.<SendAnalysisAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<GetResultFromServiceAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<GetAnalysisResultAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<WriteAnalysisReportsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPort.ConsoleApiPort.<AnalyzeAssembliesAsync>d__7.MoveNext()<---


There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
```

**VSIX Output**:

```
Microsoft (R) .NET Portability Analyzer 1.0.261.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

Using default target platforms.
To select platforms, visit Tools->Options->.NET Portability Analyzer.
Detecting assembly references                      [Done]
Sending data to service                            [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

```

**Comment by conniey** [comment]
@martincostello Thanks for reporting this.  We had updated the catalog but had not updated the default targets. It should be fixed now.

**Comment by giulianisanches** [comment]
I'm having the same issue.

Also, under the Tools -> Options, i dont get any platform or library to choose from.

Thanks.
![f1](https://cloud.githubusercontent.com/assets/81200/17646433/4d53153e-619f-11e6-8e08-cb620a70fbcf.png)
![f2](https://cloud.githubusercontent.com/assets/81200/17646432/4d52a392-619f-11e6-86c7-22c159deed20.png)

**Comment by conniey** [comment]
@giulianisanches Hi. I apologise for that. We changed our catalog updates to run every day... but the default targets were incorrect because of some changes in platform names. I fixed the service so it is working again. Can you try it again?

**Comment by giulianisanches** [comment]
Working. Thank you :)
