### ISSUE TITLE
There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

### ISSUE THREAD

**Issue by Mattacks** [Microsoft/dotnet-apiport#388]
apiport.exe analyze -f _folder_
Gives:

"There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version."

during 'Analyzing compatibbility

Reported when I have just downloaded the latest version
1.4.0-alpha-00119

When I ran it in 1.2 I got the same error, but with the following additional stack trace:

Detecting assembly references                     [Done]
Sending data to service                           [Failed]
ApiPort.exe Error: 0 : System.AggregateException: One or more errors occurred. ---> Microsoft.Fx.Portability.Portability
AnalyzerException: There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have t
he most up-to-date version.
   at Microsoft.Fx.Portability.CompressedHttpClient.<CallInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.CompressedHttpClient.<CallAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortService.<SendAnalysisAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<GetResultFromServiceAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<GetAnalysisResultAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<WriteAnalysisReportsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPort.ConsoleApiPort.<AnalyzeAssembliesAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ApiPort.Program.Main(String[] args)
---> (Inner Exception #0) Microsoft.Fx.Portability.PortabilityAnalyzerException: There was an unknown error code from th
e service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
   at Microsoft.Fx.Portability.CompressedHttpClient.<CallInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.CompressedHttpClient.<CallAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortService.<SendAnalysisAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<GetResultFromServiceAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<GetAnalysisResultAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Fx.Portability.ApiPortClient.<WriteAnalysisReportsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPort.ConsoleApiPort.<AnalyzeAssembliesAsync>d__7.MoveNext()<---

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date
version.

**Comment by conniey** [comment]
@Mattacks Would you mind checking again? There was a service degradation around the time you created this issue. The service should be up and running now.

**Comment by Mattacks** [comment]
Yes, that seems to have been it.
However, the bug was not really about the failure but the uninformative error message. Have you fixed the error message?

**Comment by rhafeez** [comment]
I have downloaded the Visual Studio extension for ".net portability analyzer" and I am getting a same error while running it on one of the project,

````
Using default target platforms.
To select platforms, visit Tools->Options->.NET Portability Analyzer.
Detecting assembly references                      [Done]
Analyzing compatibility                            [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
````
and when i go to Portability Analyzer settings then it is showing me following error,

unable to contact service. Try again later.


is that a same issue or something different? or service is not available now?

**Comment by rhafeez** [comment]
I have 1.3.0.119 version of this extension on my machine.

**Comment by EfimenkoAndrew** [comment]
I have tried to use this tool and got the next message:
Detecting assembly references                     [Done]
Analyzing compatibility                           [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
I have installed this extension approximately 10 mins ago and reinstalled again. Please help me to analyze the code

**Comment by EfimenkoAndrew** [comment]
@conniey, please take a look

**Comment by Lxiamail** [comment]
@EfimenkoAndrew Thanks for reporting the problem. This error message normally means that you got an error from APIPort's server endpoint. Can you share the reproduction steps for the issue? There is an known issue getting the same error when select dgml format when using APIPort VS extension.

**Comment by EfimenkoAndrew** [comment]
@Lxiamail you are right. Everything works fine, my mistake. Thank you very much for your help

**Comment by Lxiamail** [comment]
I'm happy to hear that everything works fine.

**Comment by alohaninja** [comment]
I had this same error today running portability analyzer in VS IDE - switching to command line worked just fine for exporting DGML...

![image](https://user-images.githubusercontent.com/26234626/92954852-03015480-f419-11ea-81b0-5c8c5e56f655.png)

**Comment by Lxiamail** [comment]
@alohaninja yes, it's a known issue, tracked by https://github.com/microsoft/dotnet-apiport/issues/896

**Comment by lalitmj** [comment]
Is this issue resolved? This fails all the time both using the console app and the Add-In when generating DGML files. The step it fails is when it contacts the external API while "Analyzing compatibility". I couldn't make it work with Offline mode as well. 

Did anybody have any workarounds or tried any other approach to build that dependency tree which is very helpful.

TIA

**Comment by pramsden** [comment]
I am using ApiPort.2.8.10 and Net runtime 3.1.22 x64 and am getting the same error.

I have tried a number of different report types DGML and HTML and it always fails.
