### ISSUE TITLE
"unknown error" and missing "system.collection.immutable" when analyzing net45 project

### ISSUE THREAD

**Issue by oising** [Microsoft/dotnet-apiport#471]
I get this in the visual studio 2017.3 tool window:

I'm not using s.c.immutable in the target project, so I'm not sure what this is about.

```
Microsoft (R) .NET Portability Analyzer 1.0.0.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

An unknown error occured.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Collections.Immutable, Version=1.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ApiPortVS.Analyze.ApiPortVsAnalyzer.<GetApiPortOptions>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at ApiPortVS.Analyze.ApiPortVsAnalyzer.GetApiPortOptions(IEnumerable`1 assemblyPaths, IEnumerable`1 formats, String reportFileName)
   at ApiPortVS.Analyze.ApiPortVsAnalyzer.<WriteAnalysisReportsAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ApiPortVS.Analyze.ProjectAnalyzer.<AnalyzeProjectAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPortVS.AnalyzeMenu.<AnalyzeProjectsAsync>d__6.MoveNext()


WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by alinapopa** [comment]
@oising This is because the VS extension was using a higher version of System.Collections.Immutable than the one that Visual Studio uses (version 1.2.1 was needed for VS 2017). PR #473 addresses this issue.
Thanks for reporting this bug!
