### ISSUE TITLE
Visual Studio extension for VS2015 fails with MissingMethodException

### ISSUE THREAD

**Issue by alinapopa** [Microsoft/dotnet-apiport#491]
Exception is occurring when trying to perform analysis using VS2015
```
System.MissingMethodException: Method not found: 'System.Collections.Immutable.IImmutableList`1<System.Collections.Generic.KeyValuePair`2<System.String,System.Collections.Immutable.IImmutableDictionary`2<System.String,System.String>>> Microsoft.VisualStudio.ProjectSystem.Build.IOutputGroup.get_Outputs()'.
   at ApiPortVS.VS2015.ProjectBuilder2015.<GetBuildOutputFilesFromCPSAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at ApiPortVS.VS2015.ProjectBuilder2015.GetBuildOutputFilesFromCPSAsync(Project project, CancellationToken cancellationToken)
   at ApiPortVS.VS2015.ProjectBuilder2015.<GetBuildOutputFilesAsync>d__1.MoveNext()`
```

**Comment by conniey** [comment]
Removed support for VS2015.
