### ISSUE TITLE
An unexpected error was encountered while parsing the metadata for the PE file [System.InvalidOperationException: Sequence contains more than one matching element]

### ISSUE THREAD

**Issue by rafael-teixeira** [Microsoft/dotnet-apiport#512]
Hello,

I am facing the issue below when try to analyze one assembly.

```
C:\Sources\Repos\dotnet-apiport\bin\Debug\ApiPort\net46\win7-x64>ApiPort.exe analyze -f "f:\temp.dll" -t ".NET Framework, Version=4.6.2" -b -r Html -o "C:\temp.html"
Microsoft (R) API Portability Analyzer vunknown
Copyright (C) Microsoft Corporation. All rights reserved.

This tool analyzes .NET assemblies to determine possible problems moving between .NET platforms (such as
Windows Store, desktop, Mono, .NET Core, etc) as well as between .NET Framework versions (ie 4.x->4.y).

To learn more about how this tool works, including the data we are collecting,
go here - http://go.microsoft.com/fwlink/?LinkId=397652

Detecting assembly references                     [Failed]

**An unexpected error was encountered while parsing the metadata for the PE file located at f:\temp.dll**.

System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Fx.Portability.Analyzer.DependencyFinderEngineHelper.GetSystemRuntimeAssemblyInformation() in C:\Sources\Repos\dotnet-apiport\src\Microsoft.Fx.Portability.MetadataReader\DependencyFinderEngineHelper.cs:line 213
   at Microsoft.Fx.Portability.Analyzer.DependencyFinderEngineHelper.ComputeData() in C:\Sources\Repos\dotnet-apiport\src\Microsoft.Fx.Portability.MetadataReader\DependencyFinderEngineHelper.cs:line 60
   at Microsoft.Fx.Portability.Analyzer.ReflectionMetadataDependencyInfo.GetDependencies(IAssemblyFile file) in C:\Sources\Repos\dotnet-apiport\src\Microsoft.Fx.Portability.MetadataReader\ReflectionMetadataDependencyInfo.cs:line 128

```

I verified the source code and the issue is taking place in the line below

```
C:\Sources\Repos\dotnet-apiport\src\Microsoft.Fx.Portability.MetadataReader\DependencyFinderEngineHelper.cs:213
var matchingAssembly = microsoftAssemblies.SingleOrDefault(x => s_systemObjectAssemblies.Contains(x.Name));

```

microsoftAssemblies collection has duplicated assembly names that causes exception on SingleOrDefault() method as below:
```

[{System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation](url)
```

**Comment by conniey** [comment]
Can you attach the binary that is causing the issue?

**Comment by twsouthwick** [comment]
Looks like this can occur when some dependent assembly will be referencing a different version of mscorlib. For instance:

- Assembly1, mscorlib 4.0.0.0
- Assembly2, mscorlib 2.0.0.0
- Assembly1 references Assembly2

For now, we can just default to the latest version (since that's the default binding redirects will do). This may represent a larger issue where we don't actually resolve anything, so binding redirects in general are missed. This is the first issue, though, that I've seen where this comes into play.

**Comment by rjvdboon** [comment]
I was about to file the same issue. I've seen two reasons for this:
- in a .Net 4 project reference a PCL (gives me mscorlib 4.0.0.0 and 2.0.5.0)
- in a .Net 4 project reference a .Net 2 library (gives me mscorlib 4.0.0.0 and 2.0.0.0)

In a private build of apiport I replaced the `SingleOrDefault(x => ...)` by `Where(x => ...).OrderByDescending(x => x.Version).FirstOrDefault()`

**Comment by rjvdboon** [comment]
In my solution the binding redirects also cause issues. Not sure if it really impacts the analysis, but it does cause warnings.

**Comment by twsouthwick** [comment]
@rjvdboon I've been trying to produce a repro of this and can't. What version of VS are you building with?

**Comment by rjvdboon** [comment]
I've been building with VS2013. The binaries I've tested against were probably built using direct csc.exe invocations. (We've got a convoluted build script involving csc /noconfig /nodefaultlibs etc.) I'll see if I can construct a minimal repro when I'm back at work.

**Comment by rjvdboon** [comment]
No full repro steps yet, but it seems to be caused at least by the use of Autofac 3.5.2.0 (Profile328). Referencing anything from that version should cause the issue, I think.

**Comment by rjvdboon** [comment]
See attached zip for a repro case. Build with Visual Studio 2013. It is a solution with two projects: a PCL library (profile328) and a consuming exe. The exe will have 2 mscorlib references (of which 1 is retargetable).
[repro.zip](https://github.com/Microsoft/dotnet-apiport/files/1491797/repro.zip)

**Comment by twsouthwick** [comment]
I don't have VS 2013 installed at the moment. I'll see if I can do that. In the meantime, can you share the exe and dll?

**Comment by twsouthwick** [comment]
I got a VM set up with VS 2013 and have a repro. I should have a fix ready soon.
