### ISSUE TITLE
Cannot analyze using VSIX. FNFException NuGet.VisualStudio

### ISSUE THREAD

**Issue by conniey** [Microsoft/dotnet-apiport#530]
**Repro Steps**
1. Fetch latest changes from master/dev
1. Start debugging ApiPort.Vsix 
1. Right-click project -> Analyze Project Portability

**Expected**
It should analyse the assembly.

**Actual**
```
Microsoft (R) .NET Portability Analyzer 2.4.0.898
Copyright (C) Microsoft Corporation. All rights reserved.
en-CAAbout Tool http://go.microsoft.com/fwlink/?LinkId=506955
en-CAView Privacy Statement https://privacy.microsoft.com/en-us/privacystatement



An unknown error occured.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.VisualStudio, Version=4.4.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.VisualStudio, Version=4.4.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ApiPortVS.Analyze.ProjectAnalyzer.GetPackageReferences(Project project)
   at ApiPortVS.Analyze.ProjectAnalyzer.<AnalyzeProjectAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at ApiPortVS.AnalyzeMenu.<AnalyzeProjectsAsync>d__7.MoveNext()

=== Pre-bind state information ===
LOG: DisplayName = NuGet.VisualStudio, Version=4.4.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/
LOG: Initial PrivatePath = NULL
Calling assembly : ApiPort.VisualStudio.Common, Version=2.4.0.898, Culture=neutral, PublicKeyToken=4a286c3e845c3e69.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\conniey\AppData\Local\Microsoft\VisualStudio\15.0_b8c4939cExp\devenv.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: NuGet.VisualStudio, Version=4.4.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/NuGet.VisualStudio/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PublicAssemblies/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PublicAssemblies/NuGet.VisualStudio/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/NuGet.VisualStudio/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.VisualStudio/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.VisualStudio/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.VisualStudio/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.VisualStudio/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.VisualStudio/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/NuGet.VisualStudio/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PublicAssemblies/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PublicAssemblies/NuGet.VisualStudio/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/NuGet.VisualStudio/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.VisualStudio/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.VisualStudio/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.VisualStudio/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.VisualStudio/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.VisualStudio/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/USERS/CONNIEY/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_B8C4939CEXP/EXTENSIONS/MICROSOFT/.NET PORTABILITY ANALYZER/2.4.0.898/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/USERS/CONNIEY/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_B8C4939CEXP/EXTENSIONS/MICROSOFT/.NET PORTABILITY ANALYZER/2.4.0.898/NuGet.VisualStudio/NuGet.VisualStudio.DLL.
LOG: Attempting download of new URL file:///C:/USERS/CONNIEY/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_B8C4939CEXP/EXTENSIONS/MICROSOFT/.NET PORTABILITY ANALYZER/2.4.0.898/NuGet.VisualStudio.EXE.
LOG: Attempting download of new URL file:///C:/USERS/CONNIEY/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_B8C4939CEXP/EXTENSIONS/MICROSOFT/.NET PORTABILITY ANALYZER/2.4.0.898/NuGet.VisualStudio/NuGet.VisualStudio.EXE.



```

**Comment by twsouthwick** [comment]
Weird - these are supposed to be embedded interop and shouldn't actually be trying to load them. Should check the build to make sure it's doing that
