### ISSUE TITLE
 Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by JerkerPihl** [microsoft/dotnet-apiport#601]
Testing on solution with different projects (Net4.6.1 and Core 1.1)

Detecting assembly references                      [Done]
* Could not find file: 'C:\git\PRJ\PRJ\src\PRJ\bin\Release\net461\PRJ.dll'
* No files were found to upload.

Finding source line information
	PRJ.dll                                        [Done]

An unknown error occured.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ApiPortVS.SourceMapping.CciMetadataTraverser..ctor(String assemblyPath, ReportingResult analysis, PdbReader pdbReader)
   at ApiPortVS.SourceMapping.CciSourceLineMapper.GetSourceInfo(String assemblyPath, String pdbPath, ReportingResult report)
   at ApiPortVS.SourceMapping.SourceLineMapper.GetSourceInfo(IEnumerable`1 assemblyPaths, ReportingResult report)
   at ApiPortVS.Analyze.ProjectAnalyzer.<>c__DisplayClass9_0.<AnalyzeProjectAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ApiPortVS.Analyze.ProjectAnalyzer.<AnalyzeProjectAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPortVS.AnalyzeMenu.<AnalyzeProjectsAsync>d__6.MoveNext()

**Comment by twsouthwick** [comment]
Hi @JerkerPihl - sorry for the slow response. Do you have a small repro we can use to test this with? Is `PRJ.dll` something that you can share with us?

**Comment by Lxiamail** [comment]
@JerkerPihl Hope you have worked on the problem. Closing the inactive issue for now. Please feel free to reopen the issue once you can share a repro.
