### ISSUE TITLE
System.InvalidOperationException: The operation failed as details for project {projectName} could not be loaded.

### ISSUE THREAD

**Issue by MIchaelMainer** [Microsoft/dotnet-apiport#678]
VS 2017, 15.7.2
.NET Portability Analyzer 2.5.0.0

I'm trying to run this analyzer against https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Microsoft.Graph.csproj.

I'm getting this exception in here: [AnalyzeMenu.cs#L57](https://github.com/Microsoft/dotnet-apiport/blob/9aed82fdd855431cfd378cf10907b4e73ba96144/src/ApiPort/ApiPort.VisualStudio/AnalyzeMenu.cs#L57)

An unknown error occured.
System.InvalidOperationException: The operation failed as details for project Microsoft.Graph could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass10_0.<<GetInstalledPackages>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)

   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at ApiPortVS.Analyze.ProjectAnalyzer.GetPackageReferences(Project project)
   at ApiPortVS.Analyze.ProjectAnalyzer.<AnalyzeProjectAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPortVS.AnalyzeMenu.<AnalyzeProjectsAsync>d__7.MoveNext()

**Comment by twsouthwick** [comment]
@conniey This looks to be a new style csproj. Did we add support for that?

**Comment by conniey** [comment]
@twsouthwick No. I don't think the new style csproj was around when I had originally coded this.

**Comment by twsouthwick** [comment]
@conniey What would it take to support this?

**Comment by twsouthwick** [comment]
With the latest changes, this seems to be working. Let us know if you're still having trouble.
