### ISSUE TITLE
Unable to resolve service for type 'System.Diagnostics.DiagnosticSource' while attempting to activate 'Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator'.

### ISSUE THREAD

**Issue by JoshMcCullough** [Microsoft/dotnet-apiport#744]
Just cloned the repo on Linux Mint 19, installed the .NET Core SDK (2.2), and ran `./build.sh` -- everything build fine until `Testing tests/lib/Microsoft.Fx.Portability.Reports.Html.Tests/Microsoft.Fx.Portability.Reports.Html.Tests.csproj`, where I get this error:

```
[xUnit.net 00:00:01.1725303]     Microsoft.Fx.Portability.Reports.Html.Tests.HtmlReportWriterTests.CreatesHtmlReport [FAIL]
Failed   Microsoft.Fx.Portability.Reports.Html.Tests.HtmlReportWriterTests.CreatesHtmlReport
Error Message:
 System.InvalidOperationException : Unable to resolve service for type 'System.Diagnostics.DiagnosticSource' while attempting to activate 'Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator'.
Stack Trace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.<>c.<AddRazorViewEngineServices>b__5_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Fx.Portability.Reports.HtmlRazorReportWriter.WriteStreamAsync(Stream stream, AnalyzeResponse response) in /home/josh/Projects/third-party/dotnet-apiport/src/lib/Microsoft.Fx.Portability.Reports.Html/HtmlRazorReportWriter.cs:line 46
   at Microsoft.Fx.Portability.Reports.Html.Tests.HtmlReportWriterTests.CreatesHtmlReport() in /home/josh/Projects/third-party/dotnet-apiport/tests/lib/Microsoft.Fx.Portability.Reports.Html.Tests/HtmlReportWriterTests.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
```

Not exactly sure what to do from here. Thanks!

**Comment by conniey** [comment]
Thanks for reporting this! :) There is a bug in running the tests. 

ApiPort probably built correctly.  You can run it by executing:
`dotnet bin/Debug/ApiPort/netcoreapp2.1/ApiPort.dll` (ex. `dotnet bin/Debug/ApiPort/netcoreapp2.1/ApiPort.dll analyze -f foo.dll`

**Comment by JoshMcCullough** [comment]
I booted back over to Windows so I could move forward, I appreciate your help though!
