### ISSUE TITLE
IOException

### ISSUE THREAD

**Issue by Logerfo** [microsoft/dotnet-apiport#803]
Visual Studio 2019 16.4.0 Preview 1.0.
.NET Portability Analyzer 1.1.10808.0.

> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary'2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Microsoft.Cci.PdbReader..ctor(Stream pdbStream, IMetadataHost host, Boolean loadSource)
   at ApiPortVS.SourceMapping.CciSourceLineMapper.GetSourceInfo(String assemblyPath, String pdbPath, ReportingResult report)
   at ApiPortVS.SourceMapping.SourceLineMapper.GetSourceInfo(IEnumerable'1 assemblyPaths, ReportingResult report)
   at ApiPortVS.Analyze.ProjectAnalyzer.<>c__DisplayClass9_0.<AnalyzeProjectAsync>b__0()
   at System.Threading.Tasks.Task'1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ApiPortVS.Analyze.ProjectAnalyzer.<AnalyzeProjectAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPortVS.AnalyzeMenu.<AnalyzeProjectsAsync>d__7.MoveNext()

**Comment by Lxiamail** [comment]
@Logerfo Thanks for reporting the issue. Have you tried latest version of[ ApiPort VS extension](https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer )

**Comment by Logerfo** [comment]
@Lxiamail I didn't, and the project I was porting back then when I opened this issue is now already ported.

**Comment by Lxiamail** [comment]
@Logerfo Sorry for the delay response due to the other priorities. Close the issue for now. Please feel free to reopen if you run into it again in latest version of ApiPort VS extension.
